---
title: "Reading_dataset"
author: "Junting Ren"
date: "November 20, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(rvest)
library(httr)
library(readxl)
library(data.table)
library(stringr)
library(janitor)
```

```{r reading the New York Inspection data}
library(tidyverse)
library(httr)
library(jsonlite)

get_all_inspections = function(url) {
  
  all_inspections = vector("list", length = 0)
  
  loop_index = 1
  chunk_size = 50000
  DO_NEXT = TRUE
  
  while (DO_NEXT) {
    message("Getting data, page ", loop_index)
    
    all_inspections[[loop_index]] = 
      GET(url,
          query = list(`$order` = "zipcode",
                       `$limit` = chunk_size,
                       `$offset` = as.integer((loop_index - 1) * chunk_size)
                       )
          ) %>%
      content("text") %>%
      fromJSON() %>%
      as_tibble()
    
    DO_NEXT = dim(all_inspections[[loop_index]])[1] == chunk_size
    loop_index = loop_index + 1
  }
  
  all_inspections
  
}

url = "https://data.cityofnewyork.us/resource/9w7m-hzhe.json"

rest_inspection = get_all_inspections(url) %>%
  bind_rows() 
```

```{r reading and cleaning the health indicator data}
download.file("https://www1.nyc.gov/assets/doh/downloads/excel/episrv/2015_CHP_PUD.xlsx", mode="wb", destfile = "health.xlsx")
health <- read_excel("health.xlsx", sheet = "CHP_all_data") %>% 
  select(Name, Racewhite_Rate, Age0to17_rate, 
         Age18to24_rate, Age25to44_rate, Poverty, Unemployment,
         Smoking, Exercise,
         Obesity, Diabetes, Stroke_Hosp) %>% 
  clean_names() %>% 
  mutate(age0to44_rate = age0to17_rate + age18to24_rate + age25to44_rate) %>% 
  select(-age0to17_rate, -age18to24_rate, -age25to44_rate)
  
```

```{r defining_fastfood}
rest_inspection %>%
  mutate(dba = str_to_upper(dba)) %>%
  arrange(cuisine_description) %>%
  count(cuisine_description)
```

```{r counting_fastfood}
name_boro = c("MANHATTAN", "BROOKLYN", "QUEENS", "BRONX", "STATEN ISLAND")

n_rest = function(name_boro){
  
  rest_boro =
    rest_inspection %>%
    filter(boro == name_boro) %>%
    distinct(camis)
  
  n_rest = nrow(rest_boro)

  n_rest    
} 

rest_fastfood = 
  rest_inspection %>%
  filter(cuisine_description %in% c("Bagels/Pretzels",
                                    "Bottled beverages, including water, sodas, juices, etc.",
                                    "Chicken",
                                    "Delicatessen",
                                    "Donuts",
                                    "Hamburgers",
                                    "Hotdogs",
                                    "Hotdogs/Pretzels",
                                    "Ice Cream, Gelato, Yogurt, Ices",
                                    "Nuts/Confectionary",
                                    "Pancakes/Waffles",
                                    "Pizza",
                                    "Soul Food",
                                    "Sandwiches"))

n_fastfood = function(name_boro){
  
  rest_fastfood_distinct = 
    rest_fastfood %>%
    filter(boro == name_boro) %>%
    distinct(camis, cuisine_description)
  
  n_fastfood = nrow(rest_fastfood_distinct)
  
  n_fastfood
}

percent_fastfood = function(name_boro){
  
  percent_fastfood = n_fastfood(name_boro)/n_rest(name_boro)
  
  tibble(
    boro = name_boro,
    percent_fastfood = percent_fastfood
  )
}

map(name_boro, percent_fastfood) %>%
  bind_rows()
```

##Percentage of grade A restaurant in different neighborhood
```{r}

```


