---
title: "link zipcode with neighbourhood"
author: "Leiyu Yue"
date: "12/1/2017"
output: html_document
---


```{r}
rest_neighbourhood = left_join(rest_inspection, zip_code_xml, by = "zipcode")

##calculating percentage neighbourhood is na
mean(is.na(rest_neighbourhood$neighborhood))
##taking out distinct zipcodes with missing neighbourhood name
zip_code_missing =
  rest_neighbourhood %>% 
  select(zipcode, neighborhood) %>% 
  filter(is.na(neighborhood)) %>% 
  distinct()
```


##Entering data for zipcode
```{r}
zip_code_xml <- rbind(zip_code_xml, c("/","Rockaways", "11697"))
zip_code_xml <- rbind(zip_code_xml, c("/","Jamaica", "11451"))
zip_code_xml <- rbind(zip_code_xml, c("/","Jamaica", "11436"))
zip_code_xml <- rbind(zip_code_xml, c("/","Jamaica", "11433"))
zip_code_xml <- rbind(zip_code_xml, c("/","Jamaica", "11430"))
zip_code_xml <- rbind(zip_code_xml, c("/","Queens Village", "11429"))
zip_code_xml <- rbind(zip_code_xml, c("/","Queens Village", "11428"))
zip_code_xml <- rbind(zip_code_xml, c("/","Queens Village", "11427"))
zip_code_xml <- rbind(zip_code_xml, c("/","Queens", "11426"))
zip_code_xml <- rbind(zip_code_xml, c("/","Jamaica", "11422"))
zip_code_xml <- rbind(zip_code_xml, c("/","Queens", "11419"))
zip_code_xml <- rbind(zip_code_xml, c("/","Queens", "11413"))
```

